Add menu component
SAtacker/quick-ftxui pull request #12
Opened 2023-02-18 20:46 UTC by Krishna-13-cyber

Signed-off-by: Krishna Narayanan <krishnanarayanan132002@gmail.com>

2023-02-19 07:11 UTC, SAtacker commented
@Krishna-13-cyber please add tests

2023-02-19 18:04 UTC, SAtacker commented
@Krishna-13-cyber Please display the asciinema in the README.md and mention the feature

2023-02-19 18:04 UTC, SAtacker requested changes
@Krishna-13-cyber please check clang-format workflow and resolve

2023-02-20 17:45 UTC, SAtacker commented on CMakeLists.txt
> +    add_executable(tests tests/test1.cpp tests/test2.cpp)
@Krishna-13-cyber I don't think you need to create a new file

2023-02-20 17:45 UTC, SAtacker commented on include/quick-ftxui.hpp
> +    boost::recursive_wrapper<input>, boost::recursive_wrapper<expression>>
This change wasn't necessary. Please undo.

2023-02-20 17:47 UTC, SAtacker commented on examples/Menu.qf
> +}
Can you please add an example with menu and button both?

2023-02-20 17:47 UTC, SAtacker requested changes
Please make the necessary changes.

2023-03-01 18:15 UTC, Krishna-13-cyber commented
Closing this PR, a new one has been opened #18 with all the suggested changes

2023-03-01 18:15 UTC, closed without merging