Add Toggle Component
SAtacker/quick-ftxui pull request #19
Opened 2023-03-05 10:39 UTC by Krishna-13-cyber

Signed-off-by: Krishna Narayanan <krishnanarayanan132002@gmail.com>

Depiction: https://asciinema.org/a/aIY1Aj86rx4asLjJVCXECNOCX

2023-03-05 13:33 UTC, SAtacker commented on include/quick-ftxui.hpp
> +using namespace std;
Please remove this.

2023-03-05 17:37 UTC, SAtacker commented on tests/test1.cpp
> +    REQUIRE(parse_helper("Horizontal{Toggle{[" Opt1 " " Opt2 "], 0}}"));
Fix `" "` marks

2023-03-05 17:37 UTC, SAtacker commented on tests/test1.cpp
> +    REQUIRE(parse_helper("Vertical{Toggle{[" Opt1 " " Opt2 "], 8}}"));
Fix `" "` marks

2023-03-05 17:39 UTC, SAtacker requested changes
Fix `" "` makrs

2023-04-07 13:55 UTC, Krishna-13-cyber commented
Closing this PR as new issued #21

2023-04-07 13:55 UTC, closed without merging