Fixing 'first' node affecting code structure
SAtacker/quick-ftxui pull request #5
Opened 2023-02-05 15:58 UTC by vrnimje

Removed code structure's dependency on the order in which the components are to be rendered

2023-02-05 21:13 UTC, SAtacker requested changes

2023-02-05 21:13 UTC, SAtacker commented on examples/Button.qf
> +        "Exit"
This change is not needed in this PR.

2023-02-05 21:13 UTC, SAtacker commented on include/quick-ftxui.hpp
>      std::list<node> rest;
Please change the name `rest` to `expr`

2023-02-05 21:13 UTC, SAtacker commented on include/quick-ftxui.hpp
>                            (std::list<client::quick_ftxui_ast::node>, rest)
Please change the name `rest` to `expr`

2023-02-05 21:13 UTC, SAtacker commented on include/quick-ftxui.hpp
> +        expression = '{' >> *node >> '}';
Add test cases that verify your changed grammar in the test suite.

2023-02-05 21:18 UTC, SAtacker commented
@vrnimje can you also add a commit that reverts this https://github.com/SAtacker/quick-ftxui/commit/2e454e32c78938290eef7af962a1b4412e02b1b7 ?

2023-02-06 05:06 UTC, vrnimje commented on examples/Button.qf
> +
https://github.com/SAtacker/quick-ftxui/pull/5#discussion_r1096807957
Removed unnecessary changes

2023-02-06 05:06 UTC, vrnimje commented on include/quick-ftxui.hpp
> +    std::list<node> expr;
https://github.com/SAtacker/quick-ftxui/pull/5#discussion_r1096808013
Changed variable name as requested

2023-02-06 05:06 UTC, vrnimje commented on include/quick-ftxui.hpp
> +                          (std::list<client::quick_ftxui_ast::node>, expr)
https://github.com/SAtacker/quick-ftxui/pull/5#discussion_r1096808038
Changed name as requested

2023-02-06 05:09 UTC, vrnimje commented on tests/test1.cpp
> +
https://github.com/SAtacker/quick-ftxui/pull/5#discussion_r1096808138
Added test case for checking grammer, using 'Input' component

2023-02-06 20:03 UTC, SAtacker commented
@vrnimje please rebase on top of master and signoff all your commits

2023-02-06 20:06 UTC, SAtacker approved these changes, later dismissed

2023-02-07 14:53 UTC, vrnimje commented
@SAtacker sorry faced some issues, didn't mean to close the PR, please review again

2023-02-07 15:00 UTC, SAtacker approved these changes

2023-02-07 17:23 UTC, merged